version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3307:3306

  web:
    container_name: django-web
    build:
      context: ./DevicesApi
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  my-nuxt-app:
    container_name: my-nuxt-app
    build: ./NuxtApi
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - web

