# Generated by Django 4.2.6 on 2023-10-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
                ('serial_num_mask', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('serial_num', models.TextField()),
                ('note', models.TextField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.equipmenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
